apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  namespace: qa
spec:
  selector:
    app: recommendationservice
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
  type: ClusterIP
